### ISSUE TITLE
Output has too many parentheses

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/IntervalConstraintProgramming.jl#143]
```
Contractor in 1 dimensions:
  - forward pass contracts to 1 dimensions
  - variables: Symbol[Symbol("x()")]
  - expression: x()() ^ 2 - 2 * x()()
```
Should be `x^2`, not `x()()^2`.

cc @yashcodes

**Comment by yashvardhan747** [comment]
My output is 
```
julia> C = Contractor(x^2 - 2*x)
Contractor in 1 dimensions:
  - forward pass contracts to 1 dimensions
  - variables: Symbol[:x]
  - expression: x() ^ 2 - 2 * x()
```
How's our outputs are different ?
Anyways, `expression` which is printed here with variables having unnecessary brackets with them is because ModelingToolkit creates expressions in this way only. I think this issue is more suited for  ModelingToolkit.jl.

**Comment by dpsanders** [comment]
No longer relevant
