### ISSUE TITLE
Unexpected paving 

### ISSUE THREAD

**Issue by mforets** [dpsanders/IntervalConstraintProgramming.jl#149]
```julia
using IntervalConstraintProgramming

julia> G1 = @constraint(1.0 + x0*t ≥ 1.2, [x0, t]);
julia> G2 = @constraint(1.0 + x0*t ≤ 1.4, [x0, t]);

julia> S = G1 ∩ G2

Separator:
  - variables: x0, t
  - expression: (1.0 + x0 * t ∈ [1.19999, ∞]) ∩ (1.0 + x0 * t ∈ [-∞, 1.40001])

julia> D = IntervalBox(-1..1, 0..0.4);

julia> inner, outer = S(D)
([0.499999, 1] × [0, 0.400001], [-1, 1] × [0, 0.400001])
```
The result `[0, 0.400001]` in the "inner" part for `t` is unexpected. Compare to the following plots that help to check that the valid contraction for `t` is `[0.2, 0.4]`  by changing the `eps` in:

```julia
plot(pave(S, D, eps).inner, lab="inner")
plot!(pave(S, D, eps).boundary, lab="boundary")
```
The transition between empty inner and non-empty inner happens for `eps` at <= 0.5.

CC: @lbenet, @aadesha.

**Comment by dpsanders** [comment]
I don't think it's supported to use variables in the interval in the right hand side. Try just moving that interval over to the left and leaving 0 on the right? This should probably be an error if its not supported.

Cc @yashcodes

**Comment by dpsanders** [comment]
Actually I don't know what it even means to have [x0, t] in the constraint like that. Try just removing it?

**Comment by dpsanders** [comment]
Oh but it seems to be doing the right thing anyway. Will try and look in more detail later

**Comment by mforets** [comment]
> Actually I don't know what it even means to have [x0, t] in the constraint like that. Try just removing it?

That use was taken from the tests, for example [this one](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/blob/master/test/runtests.jl#L145).

> Oh but it seems to be doing the right thing anyway. 

Yes; `pave(S, D, eps)` works fine, but `inner, outer = S(D)` seems to return a contradictory result.

**Comment by dpsanders** [comment]
Sorry about the delay in getting to this.

I get
```
julia> inner, outer = S(D)
([0.499999, 1] × [0.199999, 0.400001], [-1, 1] × [0, 0.400001])
```
with the result as you expected. 

Could you try with https://github.com/JuliaIntervals/IntervalContractors.jl/pull/29 ?
Otherwise I'm not sure what's going on here.

**Comment by mforets** [comment]
> Could you try with JuliaIntervals/IntervalContractors.jl#29 ?

Yes! It works in that branch 👍 .

**Comment by dpsanders** [comment]
OK great!
