### ISSUE TITLE
Add documentation for using ModelingToolkit

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/IntervalConstraintProgramming.jl#151]
cc @yashcodes

**Comment by lucaferranti** [comment]
there is an article now about it on the webpage: https://juliaintervals.github.io/pages/tutorials/tutorialConstraintProgramming/#constraint_programming_with_modelingtoolkit, does it close this issue?

**Comment by lucaferranti** [comment]
cc @dpsanders

**Comment by dpsanders** [comment]
@lucaferranti: Yes it closes the issue -- except that currently the docs here are totally broken.
Maybe we should just point there instead?

**Comment by lucaferranti** [comment]
yes I think we should add here (and in the other packages too) a link in the README.md to the webpage. The only thing I am wondering is: should the link send the user to the corresponding tutorial or just to the homepage and let the user decide what to explore?

**Comment by dpsanders** [comment]
Maybe a page with links to the docs for this particular package?
