### ISSUE TITLE
Document function macro

### ISSUE THREAD

**Issue by mforets** [dpsanders/IntervalConstraintProgramming.jl#168]
We could add an example in https://juliaintervals.github.io/IntervalConstraintProgramming.jl/latest/

Example:

```julia
using IntervalConstraintProgramming, IntervalArithmetic, Plots

dom = IntervalBox(-2 .. 2, -2 .. 2)
@function gg(x, y) = (x^4 + y^4 - 1) * (x^2 + y^2 - 2) + x^5 * y
C = @constraint gg(x, y) <= 0
p = pave(C, dom, 0.01)

plot(p.inner, lw=1, ratio=1, lab="f(x, y) ≤ 0", title="")
plot!(p.boundary, lw=1, ratio=1, lab="boundary")
```

![Screenshot from 2020-09-11 14-41-28](https://user-images.githubusercontent.com/12424594/92956498-5d141100-f43d-11ea-8446-d58067241b0f.png)

**Comment by dpsanders** [comment]
These days I would tend to do that using ModelingToolkit and a standard Julia function instead:
```jl
using IntervalConstraintProgramming, IntervalArithmetic, ModelingToolkit, Plots

dom = IntervalBox(-2..2, -2..2)
	
gg(x, y) = (x^4 + y^4 - 1) * (x^2 + y^2 - 2) + x^5 * y
	
vars = @variables x, y
	
C = Separator(vars, gg(x, y) < 0)
p = pave(C, dom, 0.05)
	
plot(p.inner, lw=0, ratio=1, lab="f(x, y) ≤ 0", title="")
plot!(p.boundary, lw=0, ratio=1, lab="boundary")
```

**Comment by lucaferranti** [comment]
We have an example about ModelingToolkit with ICP.jl in the webpage now: https://juliaintervals.github.io/pages/tutorials/tutorialConstraintProgramming/#constraint_programming_with_modelingtoolkit

**Comment by mforets** [comment]
=> this issue can be closed i suppose.
