### ISSUE TITLE
Update to using Symbolics

### ISSUE THREAD

**Issue by mforets** [dpsanders/IntervalConstraintProgramming.jl#172]
Rewrite ICP to use the new `Symbolics.jl` package.

**Comment by dpsanders** [comment]
cc @yashcodes

**Comment by mforets** [comment]
i've change the title to ".. using Symbolics" (the analogue fix in LazySets is https://github.com/JuliaReach/LazySets.jl/pull/2615 )

**Comment by dpsanders** [comment]
This is in progress on the `rewrite` branch.

**Comment by dpsanders** [comment]
https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/pull/212
