### ISSUE TITLE
constants interpolation not working on julia 1.6 upwards

### ISSUE THREAD

**Issue by lucaferranti** [dpsanders/IntervalConstraintProgramming.jl#180]
Constant interpolation does not seem to work anymore when defining constraints.

In julia 1.5
```
julia> a = 3
3

julia> S = @constraint x^2 + y^2 - $a <= 0
Separator:
  - variables: x, y
  - expression: (x ^ 2 + y ^ 2) - 3 ∈ [-∞, 0]
```

whereas in julia 1.6
```
   julia> a = 3
3

julia> S = @constraint x^2 + y^2 - $a < 0
ERROR: UndefVarError: a not defined
Stacktrace:
 [1] top-level scope
   @ ~\.julia\packages\IntervalConstraintProgramming\ThYlN\src\separator.jl:153
```

**Comment by lucaferranti** [comment]
I wonder whether this change in 1.6 is the reason of the issue (from [here](https://github.com/JuliaLang/julia/blob/v1.6.0/NEWS.md) ) 


>Macros that return :quote expressions (e.g. via Expr(:quote, ...)) were previously able to work without escaping (esc(...)) their output when needed. This has been corrected, and now esc must be used in these macros as it is in other macros.

**Comment by dpsanders** [comment]
This should no longer be necessary in v0.14. 
Please feel free to re-open if this functionality is still missing.
