### ISSUE TITLE
Re-implement contractors and separators with parameters

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/IntervalConstraintProgramming.jl#215]
The mechanism is available in ReversePropagation.jl, e.g. example [here](https://github.com/dpsanders/ReversePropagation.jl/blob/81c57bd9e1b1785076d204c22daa9bff06624b2f/test/icp.jl#L18-L19):

```
julia> ex = x^2 + a * y^2
x^2 + a*(y^2)

julia> C = forward_backward_contractor(ex, vars, [a])
#96 (generic function with 1 method)

julia> C(IntervalBox(-10..10, -10..10), 0..1, 17)
(([-1, 1], [-0.242536, 0.242536]), [0, 1800])
```

The third argument is the value of the parameter.

**Comment by schillic** [comment]
I am not very familiar with the package family, but instead of reimplementing contractors here, would it not be better to do that in [IntervalContractors.jl](https://github.com/JuliaIntervals/IntervalContractors.jl)?

**Comment by dpsanders** [comment]
Old branch [parameters](https://github.com/JuliaIntervals/IntervalConstraintProgramming.jl/tree/parameters)

**Comment by dpsanders** [comment]
@schillic: The `IntervalContractors.jl` package is for individual contractors, such as the `sin_rev` reverse function. This package integrates those into contractors for arbitrary formulas. 

We might indeed want to think about renaming the `IntervalContractors.jl` package, since I agree that this is a bit confusing.

**Comment by dpsanders** [comment]
(It's also possible that the functions from `IntervalContractors.jl` will be added back to the IntervalArithmetic.jl package.)

**Comment by dpsanders** [comment]
I believe this should no longer be necessary with the new interface, but if it is then let's re-open this issue.
