### ISSUE TITLE
Remove the macro interface?

### ISSUE THREAD

**Issue by dpsanders** [dpsanders/IntervalConstraintProgramming.jl#216]
With #212 most functionality (currently except for variables) will be available using the symbol interface.

Can we then remove the macro interface? cc @schillic

**Comment by schillic** [comment]
(I am not sure whether the question was to me.) I do not know what the macro interface is, sorry.

**Comment by dpsanders** [comment]
Sorry I wasn't clear.  I was referring to the following:

Macro interface (old):
```
C = @constraint x^2 + y^2 <= 1
```

Symbolic interface (new):
```
vars = @variables x, y
C = Constraint(x^2 + y^2 <= 1, vars)
```

The macro interface tried to be too clever by extracting the variables for you, but does not allow enough control.  I would like to get rid of it.

However in `model.jl` in #212 I started to add a `model` and macro interface that is JuMP-like.
(In fact I believe there is now support in JuMP or JuMP-related packages for a constraint programming interface like this already, so we should probably not add one here.)

**Comment by dpsanders** [comment]
Removed in #212.
